# Generated by Django 5.2.3 on 2025-06-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfer_currency", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="timestamp",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("SCHEDULED", "Scheduled"),
                ],
                max_length=50,
            ),
        ),
    ]
